<?php

/* IBIS CLIENT IS FROM http://dev.csi.cam.ac.uk/trac/lookup/browser/trunk/downloads/php */

require_once "ibis-php-client-api/ibisclient/client/IbisClientConnection.php";
require_once "ibis-php-client-api/ibisclient/methods/PersonMethods.php";

/*
 * Function is called once everytime a user logs in
 * 
 */
function rolecallldap_user_login(&$edit, $account, $category = NULL) {
    $crsid = $account->name;
    $institutions = rolecallldap_getIn($crsid);
    
    $rolemap = array(
        /* "DRUPAL ROLE NAME" => "INSTITUTION NAME from LDAP", */
        "Raven-damtpusers" => "DAMTP",
        "Raven-dpmms" => "DPMMS"
    );
    
    foreach ($rolemap as $role => $value) {
        /* user_role_load_by_name() gone in DRUPAL 8 */
	$iam = FALSE;
        $roleobj = user_role_load_by_name($role);
        if ($roleobj === FALSE) {
            $type = "Rolecall-ldap";
            $message = "Rolecall Role:". $role ." does not exist";
            $severity = WATCHDOG_WARNING;        
            watchdog($type, $message, array(), $severity);
            break;
        }
	$iam = user_has_role($roleobj->rid);
        if (in_array($value, $institutions)) {
            if ($iam) {
                //user already has role/in group
            } else {
                // add role to their account
                $roles = $account->roles + array($roleobj->rid => $role);
                $account->original = clone $account;
                user_save($account, array('roles' => $roles));
            }
        } else {
            if ($iam) {
                //remove the role from the account!
                $type = "Rolecall-ldap";
                $message = "User: ".$crsid." is not listed as a member of: ".$value." removing ".$role." from their account";
                $severity = WATCHDOG_WARNING;        
                watchdog($type, $message, array(), $severity);
                $roles = $account->roles;
                unset($roles[$roleobj->rid]);
                $account->original = clone $account;
                user_save($account, array('roles' => $roles));
            } else {
                //do nothing as user doesn't have role
            }
        }
    }   
}

/*                                                                              
  given a user CRSID return an array of institutions                            
 */
function rolecallldap_getIn($user) {
  $mem = array();
  $fetch = "all_insts";
  $conn = IbisClientConnection::createConnection();
  $pm = new PersonMethods($conn);
  $person = $pm->getPerson("crsid",$user,$fetch);
  if (is_object($person)) {
    $institutions = $person->institutions;
    foreach($institutions as $key => $value) {
        $mem[] =  $value->instid;
    }
  }
  return $mem;
}

